version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: django
    versions:
    - 3.0.7
